### ISSUE TITLE
Demo connect fail when egress recording enabled

### ISSUE THREAD

**Issue by calvin-seo** [livekit/meet#58]
I am running Livekit and Egress on EKS, and using your demo web(meet.livekit.io) as a tester. It has been working nicely so far until I started test Egress features. if I join room with the jwt, the demo page crashes and the browser console shows error logs as below,
```
framework-7751730b10fa0f74.js:9 TypeError: Cannot read properties of undefined (reading 'matchAll')
    at 590-005945d272d18427.js:1:101542
    at Array.map (<anonymous>)
    at 590-005945d272d18427.js:1:101514
    at rx (590-005945d272d18427.js:1:101958)
    at 590-005945d272d18427.js:1:100800
    at Object.useMemo (framework-7751730b10fa0f74.js:9:67913)
    at n.useMemo (framework-7751730b10fa0f74.js:25:5985)
    at rE (590-005945d272d18427.js:1:100786)
    at aD (framework-7751730b10fa0f74.js:9:61583)
    at i (framework-7751730b10fa0f74.js:9:119731)

main-cca64c2bc7b52412.js:1 TypeError: Cannot read properties of undefined (reading 'matchAll')
    at 590-005945d272d18427.js:1:101542
    at Array.map (<anonymous>)
    at 590-005945d272d18427.js:1:101514
    at rx (590-005945d272d18427.js:1:101958)
    at 590-005945d272d18427.js:1:100800
    at Object.useMemo (framework-7751730b10fa0f74.js:9:67913)
    at n.useMemo (framework-7751730b10fa0f74.js:25:5985)
    at rE (590-005945d272d18427.js:1:100786)
    at aD (framework-7751730b10fa0f74.js:9:61583)
    at i (framework-7751730b10fa0f74.js:9:119731)
```

Below is how I trigger egress recording with my application
- Whenever my application receive Room_Started Webhook, it requests RoomComposite Egress
- Whenever my application receive Track_Published Webhook, it requests TrackComposite Egress

**Comment by Ocupe** [comment]
Hey @calvin-seo, thanks for your report.
We just enabled source maps on the production build of meet.livekit.io #59. Could you reproduce the issue and include the hopefully more descriptive error message? This would be highly appreciated. 🙏

**Comment by Ocupe** [comment]
@calvin-seo The source maps are not working as expected, so you don't need to repeat the test. We are working on a solution and ping you again.
